#!/bin/bash
#######################################
# Define custom layout functions here #
#######################################
# Choose keyboard mode: 
# "Admin" for cron based or "Gaming" for real time commands
keybmode="Admin"
delay=15 # When used with cron, the script will be run every $delay seconds

function f_MR {
# give $fonction an understandable name and use "_-_" --> This is used for "cheatsheet"
	fonction=MR_-_Cancel
	f_debug $fonction
	f_libnotify 6000 "Corsair K90 $layout - $fonction" "Payload aborted"
}
function f_G01 {
 # give $fonction an understandable name and use "_-_" --> This is used for "cheatsheet"
	fonction=G01_-_function_name
	f_debug $fonction
	# Start of options  ------------------>  FILL THESE TWO LINES FOR EACH KEY !!!
	checkifrunning=1  #if set to 1, prevents this script from running twice at the same time
	mustconfirm=1     #if set to 1, this action will require you to push a key to confirm the action.
	# End of Options
	f_is_running $fonction
	f_confirm $fonction
	f_libnotify 3000 "Corsair K90 $layout - $fonction" "here" # Set your notify message here
############################  Start of custom G1 script
	echo "YOUR SCRIPT COMES HERE"
############################  End of custom G1 script
	rm tmp/$fonction #Leave this rm, it is used by f_is_running
}
function f_G02 {
# give $fonction an understandable name and use "_-_" --> This is used for "cheatsheet"
	fonction=G02_-_function_name
	f_debug $fonction
	# Start of options  ------------------>  FILL THESE TWO LINES FOR EACH KEY !!!
	checkifrunning=0  #if set to 1, prevents this script from running twice at the same time
	mustconfirm=0     #if set to 1, this action will require you to push a key to confirm the action.
	# End of Options
	f_is_running $fonction
	f_confirm $fonction
	f_libnotify 3000 "Corsair K90 $layout - $fonction" "here" # Set your notify message here
############################  Start of custom G2 script
	echo "YOUR SCRIPT COMES HERE"
############################  End of custom G2 script
	rm tmp/$fonction  #Leave the rm, it is used by f_is_running
}
function f_G03 {
 # give $fonction an understandable name and use "_-_" --> This is used for "cheatsheet"
	fonction=G03_-_function_name
	f_debug $fonction
	# Start of options  ------------------>  FILL THESE TWO LINES FOR EACH KEY !!!
	checkifrunning=0  #if set to 1, prevents this script from running twice at the same time
	mustconfirm=0     #if set to 1, this action will require you to push a key to confirm the action.
	# End of Options
	f_is_running $fonction
	f_confirm $fonction
	f_libnotify 3000 "Corsair K90 $layout - $fonction" "here" # Set your notify message here
############################  Start of custom G3 script
	echo "YOUR SCRIPT COMES HERE"
############################  End of custom G3 script
	rm tmp/$fonction #Leave the rm, it is used by f_is_running

}
function f_G04 {
# give $fonction an understandable name and use "_-_" --> This is used for "cheatsheet"
	fonction=G04_-_function_name
	f_debug $fonction
	# Start of options  ------------------>  FILL THESE TWO LINES FOR EACH KEY !!!
	checkifrunning=1  #if set to 1, prevents this script from running twice at the same time
	mustconfirm=0     #if set to 1, this action will require you to push a key to confirm the action.
	# End of Options
	f_is_running $fonction
	f_confirm $fonction
	f_libnotify 3000 "Corsair K90 $layout - $fonction" "here" # Set your notify message here
############################  Start of custom G4 script
	echo "YOUR SCRIPT COMES HERE"
############################  End of custom G4 script
	rm tmp/$fonction #Leave the rm, it is used by f_is_running
}
function f_G05 {
# give $fonction an understandable name and use "_-_" --> This is used for "cheatsheet"
	fonction=G05_-_function_name
	f_debug $fonction
	# Start of options  ------------------>  FILL THESE TWO LINES FOR EACH KEY !!!
	checkifrunning=1  #if set to 1, prevents this script from running twice at the same time
	mustconfirm=1     #if set to 1, this action will require you to push a key to confirm the action.
	# End of Options
	f_is_running $fonction
	f_confirm $fonction
	f_libnotify 3000 "Corsair K90 $layout - $fonction" "here" # Set your notify message here
############################  Start of custom G5 script
	echo "YOUR SCRIPT COMES HERE"
############################  End of custom G5 script
	rm tmp/$fonction #Leave the rm, it is used by f_is_running

}
function f_G06 {
 # give $fonction an understandable name and use "_-_" --> This is used for "cheatsheet"
	fonction=G06_-_function_name
	f_debug $fonction
	# Start of options  ------------------>  FILL THESE TWO LINES FOR EACH KEY !!!
	checkifrunning=1  #if set to 1, prevents this script from running twice at the same time
	mustconfirm=1     #if set to 1, this action will require you to push a key to confirm the action.
	# End of Options
	f_is_running $fonction
	f_confirm $fonction
	f_libnotify 3000 "Corsair K90 $layout - $fonction" "here" # Set your notify message here
############################  Start of custom G6 script
	echo "YOUR SCRIPT COMES HERE"
############################  End of custom G6 script
	rm tmp/$fonction #Leave the rm, it is used by f_is_running
}
function f_G07 {
 # give $fonction an understandable name and use "_-_" --> This is used for "cheatsheet"
	fonction=G07_-_function_name
	f_debug $fonction
	# Start of options  ------------------>  FILL THESE TWO LINES FOR EACH KEY !!!
	checkifrunning=1  #if set to 1, prevents this script from running twice at the same time
	mustconfirm=1     #if set to 1, this action will require you to push a key to confirm the action.
	# End of Options
	f_is_running $fonction
	f_confirm $fonction
	f_libnotify 3000 "Corsair K90 $layout - $fonction" "here" # Set your notify message here
############################  Start of custom G7 script
	echo "YOUR SCRIPT COMES HERE"
############################  End of custom G7 script
	rm tmp/$fonction #Leave the rm, it is used by f_is_running
}
function f_G08 {
# give $fonction an understandable name and use "_-_" --> This is used for "cheatsheet"
	fonction=G08_-_function_name
	f_debug $fonction
	# Start of options  ------------------>  FILL THESE TWO LINES FOR EACH KEY !!!
	checkifrunning=1  #if set to 1, prevents this script from running twice at the same time
	mustconfirm=1     #if set to 1, this action will require you to push a key to confirm the action.
	# End of Options
	f_is_running $fonction
	f_confirm $fonction
	f_libnotify 3000 "Corsair K90 $layout - $fonction" "here" # Set your notify message here
############################  Start of custom G8 script
	echo "YOUR SCRIPT COMES HERE"
############################  End of custom G8 script
	rm tmp/$fonction #Leave the rm, it is used by f_is_running
}
function f_G09 {
#I expect unexpected bugs on this key due to noise data it sends on another event
	echo "I would try to avoid this key"
}
function f_G10 {
 # give $fonction an understandable name and use "_-_" --> This is used for "cheatsheet"
#This script flashes a .img file on an usb stick or sd card)
# Be very carefull with this one as a wrong setting can cause massive data loss!
# Again, be sure it's sdd you want to flash, inserting an extra device can easily change device name!
	fonction=G10_-_function_name
	f_debug $fonction
	# Start of options  ------------------>  FILL THESE TWO LINES FOR EACH KEY !!!
	checkifrunning=1  #if set to 1, prevents this script from running twice at the same time
	mustconfirm=1     #if set to 1, this action will require you to push a key to confirm the action.
	# End of Options
	f_is_running $fonction
	f_confirm $fonction
	f_libnotify 3000 "Corsair K90 $layout - $fonction" "here" # Set your notify message here
############################  Start of custom G10 script
	echo "YOUR SCRIPT COMES HERE"
############################  End of custom G10 script
	rm tmp/$fonction #Leave the rm, it is used by f_is_running
}
function f_G11 {
# give $fonction an understandable name and use "_-_" --> This is used for "cheatsheet"
	fonction=G11_-_function_name
	f_debug $fonction
	# Start of options  ------------------>  FILL THESE TWO LINES FOR EACH KEY !!!
	checkifrunning=1  #if set to 1, prevents this script from running twice at the same time
	mustconfirm=1     #if set to 1, this action will require you to push a key to confirm the action.
	# End of Options
	f_is_running $fonction
	f_confirm $fonction
	f_libnotify 3000 "Corsair K90 $layout - $fonction" "here" # Set your notify message here
############################  Start of custom G11 script
	echo "YOUR SCRIPT COMES HERE"
############################  End of custom G11 script
	rm tmp/$fonction #Leave the rm, it is used by f_is_running
}
function f_G12 {
# give $fonction an understandable name and use "_-_" --> This is used for "cheatsheet"
	fonction=G12_-_function_name
	f_debug $fonction
	# Start of options  ------------------>  FILL THESE TWO LINES FOR EACH KEY !!!
	checkifrunning=1  #if set to 1, prevents this script from running twice at the same time
	mustconfirm=1     #if set to 1, this action will require you to push a key to confirm the action.
	# End of Options
	f_is_running $fonction
	f_confirm $fonction
	f_libnotify 3000 "Corsair K90 $layout - $fonction" "here" # Set your notify message here
############################  Start of custom G12 script
	echo "YOUR SCRIPT COMES HERE"
############################  End of custom G12 script
	rm tmp/$fonction #Leave the rm, it is used by f_is_running
}
function f_G13 {
# give $fonction an understandable name and use "_-_" --> This is used for "cheatsheet"
	fonction=G13_-_function_name
	f_debug $fonction
	# Start of options  ------------------>  FILL THESE TWO LINES FOR EACH KEY !!!
	checkifrunning=1  #if set to 1, prevents this script from running twice at the same time
	mustconfirm=0     #if set to 1, this action will require you to push a key to confirm the action.
	# End of Options
	f_is_running $fonction
	f_confirm $fonction
	f_libnotify 3000 "Corsair K90 $layout - $fonction" "here" # Set your notify message here
############################  Start of custom G13 script
	echo "YOUR SCRIPT COMES HERE"
############################  End of custom G13 script
	rm tmp/$fonction #Leave the rm, it is used by f_is_running	
}
function f_G14 {
 # give $fonction an understandable name and use "_-_" --> This is used for "cheatsheet"
	fonction=G14_-_function_name
	f_debug $fonction
	# Start of options  ------------------>  FILL THESE TWO LINES FOR EACH KEY !!!
	checkifrunning=1  #if set to 1, prevents this script from running twice at the same time
	mustconfirm=1     #if set to 1, this action will require you to push a key to confirm the action.
	# End of Options
	f_is_running $fonction
	f_confirm $fonction
	f_libnotify 3000 "Corsair K90 $layout - $fonction" "here" # Set your notify message here
############################  Start of custom G14 script
	echo "YOUR SCRIPT COMES HERE"
############################  End of custom G14 script
	rm tmp/$fonction #Leave the rm, it is used by f_is_running	
}
function f_G15 {
# give $fonction an understandable name and use "_-_" --> This is used for "cheatsheet"
	fonction=G15_-_function_name
	f_debug $fonction
	# Start of options  ------------------>  FILL THESE TWO LINES FOR EACH KEY !!!
	checkifrunning=0  #if set to 1, prevents this script from running twice at the same time
	mustconfirm=0     #if set to 1, this action will require you to push a key to confirm the action.
	# End of Options
	f_is_running $fonction
	f_confirm $fonction
	f_libnotify 3000 "Corsair K90 $layout - $fonction" "here" # Set your notify message here
############################  Start of custom G15 script
	echo "YOUR SCRIPT COMES HERE"
############################  End of custom G15 script
	rm tmp/$fonction #Leave the rm, it is used by f_is_running	
}
function f_G16 {
 # give $fonction an understandable name and use "_-_" --> This is used for "cheatsheet"
	fonction=G16_-_function_name
	f_debug $fonction
	# Start of options  ------------------>  FILL THESE TWO LINES FOR EACH KEY !!!
	checkifrunning=0  #if set to 1, prevents this script from running twice at the same time
	mustconfirm=0     #if set to 1, this action will require you to push a key to confirm the action.
	# End of Options
	f_is_running $fonction
	f_confirm $fonction
	f_libnotify 3000 "Corsair K90 $layout - $fonction" "here" # Set your notify message here

############################  Start of custom G16 script
	echo "YOUR SCRIPT COMES HERE"
############################  End of custom G16 script
	rm tmp/$fonction #Leave the rm, it is used by f_is_running
}
function f_G17 {
	#USE WITH CAUTION... I experienced unexpected bugs on this key due to noise data sent on another event
	echo "I would try to avoid this key"
}
function f_G18 {
	#USE WITH CAUTION... I experienced unexpected bugs on this key due to noise data sent on another event
	echo "I would try to avoid this key"
}
function f_M1 {
# give $fonction an understandable name and use "_-_" --> This is used for "cheatsheet"
	fonction=M1_-_function_name
	f_debug $fonction
	# Start of options  ------------------>  FILL THESE TWO LINES FOR EACH KEY !!!
	checkifrunning=1  #if set to 1, prevents this script from running twice at the same time
	mustconfirm=1     #if set to 1, this action will require you to push a key to confirm the action.
	# End of Options
	f_is_running $fonction
	f_confirm $fonction
	f_libnotify 3000 "Corsair K90 $layout - $fonction" "here" # Set your notify message here
############################  Start of custom M1 script
	echo "YOUR SCRIPT COMES HERE"
############################  End of custom M1 script
	rm tmp/$fonction #Leave the rm, it is used by f_is_running	
}
function f_M2 {
# give $fonction an understandable name and use "_-_" --> This is used for "cheatsheet"
	fonction=M2_-_function_name
	f_debug $fonction
	# Start of options  ------------------>  FILL THESE TWO LINES FOR EACH KEY !!!
	checkifrunning=1  #if set to 1, prevents this script from running twice at the same time
	mustconfirm=1     #if set to 1, this action will require you to push a key to confirm the action.
	# End of Options
	f_is_running $fonction
	f_confirm $fonction
	f_libnotify 3000 "Corsair K90 $layout - $fonction" "here" # Set your notify message here
############################  Start of custom M2 script
	echo "YOUR SCRIPT COMES HERE"
############################  End of custom M2 script
	rm tmp/$fonction #Leave the rm, it is used by f_is_running
}
function f_M3 {
 # give $fonction an understandable name and use "_-_" --> This is used for "cheatsheet"
	fonction=M3_-_function_name
	f_debug $fonction
	# Start of options  ------------------>  FILL THESE TWO LINES FOR EACH KEY !!!
	checkifrunning=1  #if set to 1, prevents this script from running twice at the same time
	mustconfirm=1     #if set to 1, this action will require you to push a key to confirm the action.
	# End of Options
	f_is_running $fonction
	f_confirm $fonction
	f_libnotify 3000 "Corsair K90 $layout - $fonction" "here" # Set your notify message here
############################  Start of custom M3 script
	echo "YOUR SCRIPT COMES HERE"
############################  End of custom M3 script
	rm tmp/$fonction #Leave the rm, it is used by f_is_running
}
function f_Lock {
# give $fonction an understandable name and use "_-_" --> This is used for "cheatsheet"
	fonction=Lock_-_function_name
	f_debug $fonction
	# Start of options  ------------------>  FILL THESE TWO LINES FOR EACH KEY !!!
	checkifrunning=0  #if set to 1, prevents this script from running twice at the same time
	mustconfirm=0     #if set to 1, this action will require you to push a key to confirm the action.
	# End of Options
	f_is_running $fonction
	f_confirm $fonction
	f_libnotify 3000 "Corsair K90 $layout - $fonction" "here" # Set your notify message here
############################  Start of custom Lock script
	echo "YOUR SCRIPT COMES HERE"
############################  End of custom Lock script
	rm tmp/$fonction #Leave the rm, it is used by f_is_running	
}
function f_Unlock {
 # give $fonction an understandable name and use "_-_" --> This is used for "cheatsheet"
	fonction=Unlock_-_function_name
	f_debug $fonction
	checkifrunning=0  #if set to 1, prevents this subscript from running twice at the same time
	mustconfirm=0     #if set to 1, this action will require you to push a key to confirm the action.
	f_is_running $fonction
	f_confirm $fonction
	f_libnotify 3000 "Corsair K90 $layout - $fonction" "here" # Set your notify message here
############################  Start of custom Unlock script
	echo "YOUR SCRIPT COMES HERE"
############################  End of custom Unlock script
	rm tmp/$fonction #Leave the rm, it is used by f_is_running
}